#!/usr/bin/env bash

#alias cs_com='COMPOSER=dev.json composer install --working-dir=application/commerce'
#alias support='xclip -sel clip < /home/ajax/.support'

alias oroecd='app/console oro:entity-config:debug'
alias codesniff='usr/local/bin/phpcs -p --encoding=utf-8 --extensions=php --standard=/home/ajax/www/standards/cs/ruleset.xml'

#ORO INSTALL
alias oroup='app/console oro:platform:update --force --timeout=100000'
alias oroin='app/console oro:install --organization-name Oro --user-name admin --user-email max@oroinc.com --user-firstname Maxym --user-lastname Perepelytsya --user-password admin --sample-data y --application-url http://crmee.a --timeout 1000'
alias oroinnd='app/console oro:install --organization-name Oro --user-name admin --user-email max@oroinc.com --user-firstname Maxym --user-lastname Perepelytsya --user-password admin --sample-data n --application-url http://crmee.a --timeout 1000'
alias oroin20='app/console oro:install --organization-name Oro --user-name admin --user-email max@oroinc.com --user-firstname Maxym --user-lastname Perepelytsya --user-password admin --sample-data y --application-url http://crmee20.a --timeout 1000'
alias oroinnd20='app/console oro:install --organization-name Oro --user-name admin --user-email max@oroinc.com --user-firstname Maxym --user-lastname Perepelytsya --user-password admin --sample-data n --application-url http://crmee20.a --timeout 1000'

alias oroincce='app/console oro:install --organization-name Oro --user-name admin --user-email zebimax@gmail.com --user-firstname Maxym --user-lastname Perepelytsya --user-password admin --sample-data n --application-url http://cce.a --timeout 1000'
alias oroincce_demo='app/console oro:install --organization-name Oro --user-name admin --user-email zebimax@gmail.com --user-firstname Maxym --user-lastname Perepelytsya --user-password admin --sample-data y --application-url http://cce.a --timeout 1000'

alias cs_crm_ee='COMPOSER=dev.json composer install --working-dir=application/crm-enterprise'
alias cs_com_ee='COMPOSER=dev.json composer install --working-dir=application/commerce-enterprise'
alias cs_crm='COMPOSER=dev.json composer install --working-dir=application/crm'
alias cs_com_crm_ee='COMPOSER=dev.json composer install --working-dir=application/commerce-crm-ee'
alias cs_com='COMPOSER=dev.json composer install --working-dir=application/commerce'

#ORO TESTS
alias orointests='php app/console oro:install -v --user-name=admin --user-email=admin@example.com --user-firstname=John --user-lastname=Doe --user-password=admin --drop-database --organization-name=OroCRM --application-url=http://localhost --sample-data=n --env=test --symlink --skip-translations --skip-assets --no-debug'
alias oroin12tests='php app/console oro:install -v --user-name=admin --user-email=admin@example.com --user-firstname=John --user-lastname=Doe --user-password=admin --drop-database --organization-name=OroCRM --application-url=http://localhost --sample-data=n --env=test --symlink --skip-assets --no-debug'
alias func_tests='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional'
alias unit_tests='php -d zend.enable_gc=0 bin/phpunit --testsuite=unit'
alias func_tests_14='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-1-of-4'
alias func_tests_24='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-2-of-4'
alias func_tests_34='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-3-of-4'
alias func_tests_44='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-4-of-4'
alias func_tests_16='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-1-of-6'
alias func_tests_26='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-2-of-6'
alias func_tests_36='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-3-of-6'
alias func_tests_46='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-4-of-6'
alias func_tests_56='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-5-of-6'
alias func_tests_66='php -d zend.enable_gc=0 bin/phpunit --testsuite=functional-6-of-6'


# ORO_EXTEND
alias oroecd_ev_auth_status='app/console oro:entity-config:debug "Extend\Entity\EV_Auth_Status"'
alias oroecd_ev_ce_attendee_status='app/console oro:entity-config:debug "Extend\Entity\EV_Ce_Attendee_Status"'
alias oroecd_ev_ce_attendee_type='app/console oro:entity-config:debug "Extend\Entity\EV_Ce_Attendee_Type"'
alias oroecd_ev_dm_ab_cnt_exp_type='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Ab_Cnt_Exp_Type"'
alias oroecd_ev_dm_ab_visibility='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Ab_Visibility"'
alias oroecd_ev_dm_cmp_reply_action='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Cmp_Reply_Action"'
alias oroecd_ev_dm_cmp_status='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Cmp_Status"'
alias oroecd_ev_dm_cnt_email_type='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Cnt_Email_Type"'
alias oroecd_ev_dm_cnt_opt_in_type='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Cnt_Opt_In_Type"'
alias oroecd_ev_dm_cnt_status='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Cnt_Status"'
alias oroecd_ev_dm_df_type='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Df_Type"'
alias oroecd_ev_dm_df_visibility='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Df_Visibility"'
alias oroecd_ev_dm_import_status='app/console oro:entity-config:debug "Extend\Entity\EV_Dm_Import_Status"'
alias oroecd_ev_lead_source='app/console oro:entity-config:debug "Extend\Entity\EV_Lead_Source"'
alias oroecd_ev_lead_status='app/console oro:entity-config:debug "Extend\Entity\EV_Lead_Status"'
alias oroecd_ev_mage_subscr_status='app/console oro:entity-config:debug "Extend\Entity\EV_Mage_Subscr_Status"'
alias oroecd_ev_opportunity_status='app/console oro:entity-config:debug "Extend\Entity\EV_Opportunity_Status"'
alias oroecd_ev_task_status='app/console oro:entity-config:debug "Extend\Entity\EV_Task_Status"'
alias oroecd_abandonedcartabandonedcartcampaign='app/console oro:entity-config:debug "Oro\Bundle\AbandonedCartBundle\Entity\AbandonedCartCampaign"'
alias oroecd_accountaccount='app/console oro:entity-config:debug "Oro\Bundle\AccountBundle\Entity\Account"'
alias oroecd_activitylistactivitylist='app/console oro:entity-config:debug "Oro\Bundle\ActivityListBundle\Entity\ActivityList"'
alias oroecd_addressaddress='app/console oro:entity-config:debug "Oro\Bundle\AddressBundle\Entity\Address"'
alias oroecd_addressaddresstype='app/console oro:entity-config:debug "Oro\Bundle\AddressBundle\Entity\AddressType"'
alias oroecd_addresscountry='app/console oro:entity-config:debug "Oro\Bundle\AddressBundle\Entity\Country"'
alias oroecd_addressregion='app/console oro:entity-config:debug "Oro\Bundle\AddressBundle\Entity\Region"'
alias oroecd_analyticsrfmmetriccategory='app/console oro:entity-config:debug "Oro\Bundle\AnalyticsBundle\Entity\RFMMetricCategory"'
alias oroecd_attachmentattachment='app/console oro:entity-config:debug "Oro\Bundle\AttachmentBundle\Entity\Attachment"'
alias oroecd_attachmentfile='app/console oro:entity-config:debug "Oro\Bundle\AttachmentBundle\Entity\File"'
alias oroecd_calendarattendee='app/console oro:entity-config:debug "Oro\Bundle\CalendarBundle\Entity\Attendee"'
alias oroecd_calendarcalendar='app/console oro:entity-config:debug "Oro\Bundle\CalendarBundle\Entity\Calendar"'
alias oroecd_calendarcalendarevent='app/console oro:entity-config:debug "Oro\Bundle\CalendarBundle\Entity\CalendarEvent"'
alias oroecd_calendarcalendarproperty='app/console oro:entity-config:debug "Oro\Bundle\CalendarBundle\Entity\CalendarProperty"'
alias oroecd_calendarsystemcalendar='app/console oro:entity-config:debug "Oro\Bundle\CalendarBundle\Entity\SystemCalendar"'
alias oroecd_callcall='app/console oro:entity-config:debug "Oro\Bundle\CallBundle\Entity\Call"'
alias oroecd_callcalldirection='app/console oro:entity-config:debug "Oro\Bundle\CallBundle\Entity\CallDirection"'
alias oroecd_callcallstatus='app/console oro:entity-config:debug "Oro\Bundle\CallBundle\Entity\CallStatus"'
alias oroecd_campaigncampaign='app/console oro:entity-config:debug "Oro\Bundle\CampaignBundle\Entity\Campaign"'
alias oroecd_campaignemailcampaign='app/console oro:entity-config:debug "Oro\Bundle\CampaignBundle\Entity\EmailCampaign"'
alias oroecd_campaignemailcampaignstatistics='app/console oro:entity-config:debug "Oro\Bundle\CampaignBundle\Entity\EmailCampaignStatistics"'
alias oroecd_casecasecomment='app/console oro:entity-config:debug "Oro\Bundle\CaseBundle\Entity\CaseComment"'
alias oroecd_casecase='app/console oro:entity-config:debug "Oro\Bundle\CaseBundle\Entity\CaseEntity"'
alias oroecd_casecasepriority='app/console oro:entity-config:debug "Oro\Bundle\CaseBundle\Entity\CasePriority"'
alias oroecd_casecasesource='app/console oro:entity-config:debug "Oro\Bundle\CaseBundle\Entity\CaseSource"'
alias oroecd_casecasestatus='app/console oro:entity-config:debug "Oro\Bundle\CaseBundle\Entity\CaseStatus"'
alias oroecd_channelchannel='app/console oro:entity-config:debug "Oro\Bundle\ChannelBundle\Entity\Channel"'
alias oroecd_channelcustomeridentity='app/console oro:entity-config:debug "Oro\Bundle\ChannelBundle\Entity\CustomerIdentity"'
alias oroecd_commentcomment='app/console oro:entity-config:debug "Oro\Bundle\CommentBundle\Entity\Comment"'
alias oroecd_contactcontact='app/console oro:entity-config:debug "Oro\Bundle\ContactBundle\Entity\Contact"'
alias oroecd_contactcontactaddress='app/console oro:entity-config:debug "Oro\Bundle\ContactBundle\Entity\ContactAddress"'
alias oroecd_contactcontactemail='app/console oro:entity-config:debug "Oro\Bundle\ContactBundle\Entity\ContactEmail"'
alias oroecd_contactcontactphone='app/console oro:entity-config:debug "Oro\Bundle\ContactBundle\Entity\ContactPhone"'
alias oroecd_contactgroup='app/console oro:entity-config:debug "Oro\Bundle\ContactBundle\Entity\Group"'
alias oroecd_contactmethod='app/console oro:entity-config:debug "Oro\Bundle\ContactBundle\Entity\Method"'
alias oroecd_contactsource='app/console oro:entity-config:debug "Oro\Bundle\ContactBundle\Entity\Source"'
alias oroecd_contactuscontactreason='app/console oro:entity-config:debug "Oro\Bundle\ContactUsBundle\Entity\ContactReason"'
alias oroecd_contactuscontactrequest='app/console oro:entity-config:debug "Oro\Bundle\ContactUsBundle\Entity\ContactRequest"'
alias oroecd_cronschedule='app/console oro:entity-config:debug "Oro\Bundle\CronBundle\Entity\Schedule"'
alias oroecd_dashboarddashboard='app/console oro:entity-config:debug "Oro\Bundle\DashboardBundle\Entity\Dashboard"'
alias oroecd_dataauditauditfield='app/console oro:entity-config:debug "Oro\Bundle\DataAuditBundle\Entity\AuditField"'
alias oroecd_datagridgridview='app/console oro:entity-config:debug "Oro\Bundle\DataGridBundle\Entity\GridView"'
alias oroecd_dotmaileractivity='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\Activity"'
alias oroecd_dotmaileraddressbook='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\AddressBook"'
alias oroecd_dotmaileraddressbookcontact='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\AddressBookContact"'
alias oroecd_dotmaileraddressbookcontactsexport='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\AddressBookContactsExport"'
alias oroecd_dotmailercampaign='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\Campaign"'
alias oroecd_dotmailercampaignsummary='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\CampaignSummary"'
alias oroecd_dotmailerchangedfieldlog='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\ChangedFieldLog"'
alias oroecd_dotmailercontact='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\Contact"'
alias oroecd_dotmailerdatafield='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\DataField"'
alias oroecd_dotmailerdatafieldmapping='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\DataFieldMapping"'
alias oroecd_dotmailerdatafieldmappingconfig='app/console oro:entity-config:debug "Oro\Bundle\DotmailerBundle\Entity\DataFieldMappingConfig"'
alias oroecd_emailemail='app/console oro:entity-config:debug "Oro\Bundle\EmailBundle\Entity\Email"'
alias oroecd_emailemailtemplate='app/console oro:entity-config:debug "Oro\Bundle\EmailBundle\Entity\EmailTemplate"'
alias oroecd_emailemailuser='app/console oro:entity-config:debug "Oro\Bundle\EmailBundle\Entity\EmailUser"'
alias oroecd_emailmailbox='app/console oro:entity-config:debug "Oro\Bundle\EmailBundle\Entity\Mailbox"'
alias oroecd_embeddedformembeddedform='app/console oro:entity-config:debug "Oro\Bundle\EmbeddedFormBundle\Entity\EmbeddedForm"'
alias oroecd_fieldfallbackvalue='app/console oro:entity-config:debug "Oro\Bundle\EntityBundle\Entity\EntityFieldFallbackValue"'
alias oroecd_configattributeattributefamily='app/console oro:entity-config:debug "Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeFamily"'
alias oroecd_configattributeattributegroup='app/console oro:entity-config:debug "Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeGroup"'
alias oroecd_integrationchannel='app/console oro:entity-config:debug "Oro\Bundle\IntegrationBundle\Entity\Channel"'
alias oroecd_localelocalization='app/console oro:entity-config:debug "Oro\Bundle\LocaleBundle\Entity\Localization"'
alias oroecd_localelocalizedfallbackvalue='app/console oro:entity-config:debug "Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue"'
alias oroecd_magentoaddress='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\Address"'
alias oroecd_magentocart='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\Cart"'
alias oroecd_magentocartaddress='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\CartAddress"'
alias oroecd_magentocartitem='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\CartItem"'
alias oroecd_magentocartstatus='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\CartStatus"'
alias oroecd_magentocustomer='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\Customer"'
alias oroecd_magentocustomergroup='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\CustomerGroup"'
alias oroecd_magentonewslettersubscriber='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\NewsletterSubscriber"'
alias oroecd_magentoorder='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\Order"'
alias oroecd_magentoorderaddress='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\OrderAddress"'
alias oroecd_magentoorderitem='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\OrderItem"'
alias oroecd_magentoproduct='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\Product"'
alias oroecd_magentostore='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\Store"'
alias oroecd_magentowebsite='app/console oro:entity-config:debug "Oro\Bundle\MagentoBundle\Entity\Website"'
alias oroecd_mailchimpcampaign='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\Campaign"'
alias oroecd_mailchimpextendedmergevar='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\ExtendedMergeVar"'
alias oroecd_mailchimpmember='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\Member"'
alias oroecd_mailchimpmemberactivity='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\MemberActivity"'
alias oroecd_mailchimpmemberextendedmergevar='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\MemberExtendedMergeVar"'
alias oroecd_mailchimpstaticsegment='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\StaticSegment"'
alias oroecd_mailchimpstaticsegmentmember='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\StaticSegmentMember"'
alias oroecd_mailchimpsubscriberslist='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\SubscribersList"'
alias oroecd_mailchimptemplate='app/console oro:entity-config:debug "Oro\Bundle\MailChimpBundle\Entity\Template"'
alias oroecd_marketinglistmarketinglist='app/console oro:entity-config:debug "Oro\Bundle\MarketingListBundle\Entity\MarketingList"'
alias oroecd_marketinglistmarketinglistitem='app/console oro:entity-config:debug "Oro\Bundle\MarketingListBundle\Entity\MarketingListItem"'
alias oroecd_marketinglistmarketinglisttype='app/console oro:entity-config:debug "Oro\Bundle\MarketingListBundle\Entity\MarketingListType"'
alias oroecd_multicurrencyrate='app/console oro:entity-config:debug "Oro\Bundle\MultiCurrencyBundle\Entity\Rate"'
alias oroecd_navigationmenuupdate='app/console oro:entity-config:debug "Oro\Bundle\NavigationBundle\Entity\MenuUpdate"'
alias oroecd_notenote='app/console oro:entity-config:debug "Oro\Bundle\NoteBundle\Entity\Note"'
alias oroecd_notificationemailnotification='app/console oro:entity-config:debug "Oro\Bundle\NotificationBundle\Entity\EmailNotification"'
alias oroecd_notificationmassnotification='app/console oro:entity-config:debug "Oro\Bundle\NotificationBundle\Entity\MassNotification"'
alias oroecd_organizationbusinessunit='app/console oro:entity-config:debug "Oro\Bundle\OrganizationBundle\Entity\BusinessUnit"'
alias oroecd_organizationorganization='app/console oro:entity-config:debug "Oro\Bundle\OrganizationBundle\Entity\Organization"'
alias oroecd_reminderreminder='app/console oro:entity-config:debug "Oro\Bundle\ReminderBundle\Entity\Reminder"'
alias oroecd_reportreport='app/console oro:entity-config:debug "Oro\Bundle\ReportBundle\Entity\Report"'
alias oroecd_salesb2bcustomer='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\B2bCustomer"'
alias oroecd_salesb2bcustomeremail='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\B2bCustomerEmail"'
alias oroecd_salesb2bcustomerphone='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\B2bCustomerPhone"'
alias oroecd_salescustomer='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\Customer"'
alias oroecd_saleslead='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\Lead"'
alias oroecd_salesleadaddress='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\LeadAddress"'
alias oroecd_salesleademail='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\LeadEmail"'
alias oroecd_salesleadphone='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\LeadPhone"'
alias oroecd_salesleadstatus='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\LeadStatus"'
alias oroecd_salesopportunity='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\Opportunity"'
alias oroecd_salesopportunityclosereason='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\OpportunityCloseReason"'
alias oroecd_salesopportunitystatus='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\OpportunityStatus"'
alias oroecd_salessalesfunnel='app/console oro:entity-config:debug "Oro\Bundle\SalesBundle\Entity\SalesFunnel"'
alias oroecd_scopescope='app/console oro:entity-config:debug "Oro\Bundle\ScopeBundle\Entity\Scope"'
alias oroecd_segmentsegment='app/console oro:entity-config:debug "Oro\Bundle\SegmentBundle\Entity\Segment"'
alias oroecd_tagtag='app/console oro:entity-config:debug "Oro\Bundle\TagBundle\Entity\Tag"'
alias oroecd_tagtagging='app/console oro:entity-config:debug "Oro\Bundle\TagBundle\Entity\Tagging"'
alias oroecd_tagtaxonomy='app/console oro:entity-config:debug "Oro\Bundle\TagBundle\Entity\Taxonomy"'
alias oroecd_tasktask='app/console oro:entity-config:debug "Oro\Bundle\TaskBundle\Entity\Task"'
alias oroecd_tasktaskpriority='app/console oro:entity-config:debug "Oro\Bundle\TaskBundle\Entity\TaskPriority"'
alias oroecd_trackingtrackingdata='app/console oro:entity-config:debug "Oro\Bundle\TrackingBundle\Entity\TrackingData"'
alias oroecd_trackingtrackingevent='app/console oro:entity-config:debug "Oro\Bundle\TrackingBundle\Entity\TrackingEvent"'
alias oroecd_trackingtrackingeventdictionary='app/console oro:entity-config:debug "Oro\Bundle\TrackingBundle\Entity\TrackingEventDictionary"'
alias oroecd_trackingtrackingvisit='app/console oro:entity-config:debug "Oro\Bundle\TrackingBundle\Entity\TrackingVisit"'
alias oroecd_trackingtrackingvisitevent='app/console oro:entity-config:debug "Oro\Bundle\TrackingBundle\Entity\TrackingVisitEvent"'
alias oroecd_trackingtrackingwebsite='app/console oro:entity-config:debug "Oro\Bundle\TrackingBundle\Entity\TrackingWebsite"'
alias oroecd_translationlanguage='app/console oro:entity-config:debug "Oro\Bundle\TranslationBundle\Entity\Language"'
alias oroecd_useremail='app/console oro:entity-config:debug "Oro\Bundle\UserBundle\Entity\Email"'
alias oroecd_usergroup='app/console oro:entity-config:debug "Oro\Bundle\UserBundle\Entity\Group"'
alias oroecd_userimpersonation='app/console oro:entity-config:debug "Oro\Bundle\UserBundle\Entity\Impersonation"'
alias oroecd_userrole='app/console oro:entity-config:debug "Oro\Bundle\UserBundle\Entity\Role"'
alias oroecd_useruser='app/console oro:entity-config:debug "Oro\Bundle\UserBundle\Entity\User"'
alias oroecd_workflowbasetransitiontrigger='app/console oro:entity-config:debug "Oro\Bundle\WorkflowBundle\Entity\BaseTransitionTrigger"'
alias oroecd_workflowprocessdefinition='app/console oro:entity-config:debug "Oro\Bundle\WorkflowBundle\Entity\ProcessDefinition"'
alias oroecd_workflowprocesstrigger='app/console oro:entity-config:debug "Oro\Bundle\WorkflowBundle\Entity\ProcessTrigger"'
alias oroecd_workflowtransitioncrontrigger='app/console oro:entity-config:debug "Oro\Bundle\WorkflowBundle\Entity\TransitionCronTrigger"'
alias oroecd_workflowtransitioneventtrigger='app/console oro:entity-config:debug "Oro\Bundle\WorkflowBundle\Entity\TransitionEventTrigger"'
alias oroecd_workflowworkflowdefinition='app/console oro:entity-config:debug "Oro\Bundle\WorkflowBundle\Entity\WorkflowDefinition"'
alias oroecd_workflowworkflowitem='app/console oro:entity-config:debug "Oro\Bundle\WorkflowBundle\Entity\WorkflowItem"'
alias oroecd_workflowworkflowstep='app/console oro:entity-config:debug "Oro\Bundle\WorkflowBundle\Entity\WorkflowStep"'
alias oroecd_zendeskticket='app/console oro:entity-config:debug "Oro\Bundle\ZendeskBundle\Entity\Ticket"'
alias oroecd_zendeskticketcomment='app/console oro:entity-config:debug "Oro\Bundle\ZendeskBundle\Entity\TicketComment"'
alias oroecd_zendeskticketpriority='app/console oro:entity-config:debug "Oro\Bundle\ZendeskBundle\Entity\TicketPriority"'
alias oroecd_zendeskticketstatus='app/console oro:entity-config:debug "Oro\Bundle\ZendeskBundle\Entity\TicketStatus"'
alias oroecd_zendesktickettype='app/console oro:entity-config:debug "Oro\Bundle\ZendeskBundle\Entity\TicketType"'
alias oroecd_zendeskuser='app/console oro:entity-config:debug "Oro\Bundle\ZendeskBundle\Entity\User"'
alias oroecd_zendeskuserrole='app/console oro:entity-config:debug "Oro\Bundle\ZendeskBundle\Entity\UserRole"'
alias oroecd_zendeskzendeskresttransport='app/console oro:entity-config:debug "Oro\Bundle\ZendeskBundle\Entity\ZendeskRestTransport"'

#alias rcsu='/usr/bin/time app/console oro:message-queue:consume --env prod'
#
#
#alias cdcrm='cd application/crm'
#alias cdcrme='cd application/crm-enterprise'
#alias cdcom='cd application/commerce'
#alias cdcome='cd application/commerce-enterprise'
#alias cdcce='cd application/commerce-crm-ee'
#alias cdplatf='cd application/platform'
